// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuestionBankID = "question_bank_id"

// QuestionBankID 题目ID生成表
type QuestionBankID struct {
	ID         int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:自增ID，作为题目ID" json:"id"`             // 自增ID，作为题目ID
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:生成时间" json:"create_time"` // 生成时间
}

// TableName QuestionBankID's table name
func (*QuestionBankID) TableName() string {
	return TableNameQuestionBankID
}
