// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuestionBank = "question_bank"

// QuestionBank 题库
type QuestionBank struct {
	ID            int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:题目ID" json:"id"`                    // 题目ID
	SubjectID     int32     `gorm:"column:subject_id;type:int unsigned;not null;comment:题目ID" json:"subject_id"`                         // 题目ID
	LangID        int32     `gorm:"column:lang_id;type:tinyint unsigned;not null;default:1;comment:语言ID" json:"lang_id"`                 // 语言ID
	Question      string    `gorm:"column:question;type:varchar(500);not null;comment:问题" json:"question"`                               // 问题
	Option1       string    `gorm:"column:option_1;type:varchar(100);not null;comment:答案1" json:"option_1"`                              // 答案1
	Option2       string    `gorm:"column:option_2;type:varchar(100);not null;comment:答案2" json:"option_2"`                              // 答案2
	CorrectAnswer int32     `gorm:"column:correct_answer;type:tinyint unsigned;not null;comment:正确答案ID" json:"correct_answer"`           // 正确答案ID
	CreateTime    time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName QuestionBank's table name
func (*QuestionBank) TableName() string {
	return TableNameQuestionBank
}
