// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNewsLove = "news_love"

// NewsLove 资讯喜爱度记录表
type NewsLove struct {
	ID              int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                             // 主键ID
	NewsID          int32     `gorm:"column:news_id;type:int unsigned;not null;comment:资讯ID" json:"news_id"`                               // 资讯ID
	ContentType     int32     `gorm:"column:content_type;type:tinyint unsigned;not null;comment:内容类型 1:图文 2:视频 3:短视频" json:"content_type"` // 内容类型 1:图文 2:视频 3:短视频
	CategoryID      int32     `gorm:"column:category_id;type:int unsigned;not null;comment:归属大类" json:"category_id"`                       // 归属大类
	LoveScore       int32     `gorm:"column:love_score;type:int;not null;comment:喜爱分" json:"love_score"`                                   // 喜爱分
	SourceTimestamp int32     `gorm:"column:source_timestamp;type:int unsigned;not null;comment:资讯发布时间戳" json:"source_timestamp"`          // 资讯发布时间戳
	UpdateTime      time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	CreateTime      time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName NewsLove's table name
func (*NewsLove) TableName() string {
	return TableNameNewsLove
}
